### ISSUE TITLE
console (not only)

### ISSUE THREAD

**Issue by chdelfosse** [epeios-q37/atlas-python#8]
congratulations and thank you for this project

I wondered if an access to the user console would be possible,
as the only debug tool I see at present is to fire an alert()

also : disable-element() blocks silently when [erroneously] called on a div, could possibly be a no-op or yield a warning

**Comment by epeios-q37** [comment]
Thanks! Glad you enjoy my toolkit.

> I wondered if an access to the user console would be possible

I suppose you would be interested by the equivalent of the `console.log(…)` of *JavaScript*. Wouldn't it be better to use *Python* to write debugging messages in the console from which the application is launched?

> disable-element() blocks silently when [erroneously] called on a div

I was not able to reproduce this issue. Here is the code used for testing: https://replit.com/@AtlasTK/DIVDisablingBlocks. Can you please provide an example, possibly by forking and modifying this *Replit*-hosted code accordingly?

**Comment by chdelfosse** [comment]
I tried "print ()" AFTER the problem arose, and it did not work, hence my
request

In a clean state, "print()" works and is certainly the better solution

As to "disable-element()", I did not check-point the wrong version, but I
will restore it from memory (for the sake of the project)
and send it to you

thanks again,
regards

ch

**Comment by epeios-q37** [comment]
A new version of the *Atlas* toolkit is available, which provides a [log function](https://atlastk.org/api/en#log). Simply call `dom.log("message")` from a callback, and `message` will be displayed in the web console.

Regards.

Claude.

**Comment by chdelfosse** [comment]
splendid, thank you,
I will get it when my main occupation gives me some time to spare
thanks again
ch

**Comment by chdelfosse** [comment]
thank you again, most helpul when you use Google's inspector console
ch

**Comment by epeios-q37** [comment]
Pleased that it meets your expectations.
To make these messages easier to spot, the debugging messages from the toolkit itself have also been removed. So now only the messages from the browser itself remain.
